### ISSUE TITLE
Online public notice - include year-based timeline of operations

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#203]
As legal staff working on FOM regulations 
I want a statement on the online public notice for each FOM regarding the planned duration of operations using the following wording: "Road construction and harvesting of cutblocks depicted on this Forest Operations Map is scheduled to be conducted between YYYY and YYYY." where YYYY is the start and end years entered by the licensee in the Create/Edit Online Public Notice screen. 
so that legal requirements are met.

**Tasks **
-moved to #222 Add database columns for start & end year to the public_notice entity
- moved to #222 Modify API back-end to accept these fields
- Modify Admin front-end to prompt for these fields on the Create/Edit Online Public Notice screen. Use picker for the year, minimum value will be current year, maximum value will be current year + 7. 
- Validation logic to treat these as mandatory fields. End year must be >= start year.
- To confirm default value, could either be blank, or use current year, or use min/max year of development_date of FOM objects. Start by keeping it simple, start date defaults to current year, end date defaults to blank.
- Modify Public - online public notice to provide this statement, likely next to the other dates (exact layout TBD)
- pre-existing notices will leave dates blank and not show the statement in the public notice.
- Will need to demo functionality to Julius (and/or share screenshots).
- Need to clarify what Julius wants to do for his testing and whether he needs this in the demo environment.

**Acceptance Criteria**
- Given a new FOM, I can create the online public notice and pick reasonable years. I am unable to pick a year in the past or a year far in the future.
- Given an existing FOM in initial state with an existing online public notice, I can edit the online public notice and change the start/end year values. Validation rules will prevent end < start year.
- Given a published FOM with an online public notice that has reached the commenting open date, I can view it in the Public site, see the online public notice, and see the statement with the start/end years.
- Given a FOM created, published, and in commenting open prior to this change being deployed, I can view the online public notice and not have the system crash (business behavior to be determined).

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by ianliuwk1019** [comment]
There was a strange bug found by Anne-Marie while testing on dev environment which led her to be able to enter year in the past or in future that is not in the year range provided from the date-picker. 

The input box was disabled for manually entering and only allows for users to use date-picker to pick the year. This works locally but strangely not working in deployed dev environment provided it happens on the same browsers(Edge/Chrome). This bug is unknown, but I found an alternative solution to disable the input.
Also added additional class-validator at backend to validate year should not be less than current year.

**Comment by ArogeG** [comment]
Bug fixes has been pushed to test for Anne-Marie

**Comment by ianliuwk1019** [comment]
Julius reviewed the FOM TEST environment and mentioned the functionality is good.
He suggested to change the label (minor change) to remove "Proposed" wording from the frontend label for the new fields to "Start of Operations" and "End of Operations".
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/24ab16b5-37d0-434d-a5bb-1a2c9f76d3ea)

**Comment by ianliuwk1019** [comment]
While Anne-Marie was testing on new PR for the minor label change that deploy from pipeline to 'dev' she found that the existing public-notices (4 current test data) on the public frontend **does not** have the new fields show up (for Years of Operations) while she checked the admin frontend with the same FOM record and the Years of Operations appear in admin.
There was no code change for public frontend and only admin that time, nothing is wrong for public code and I checked with that as well after discussion with Anne-Marie.

However, while looking into frontend code, I also changed one more label at frontend although it was not mentioned from business, but just need to keep it consistent with the labeling change at admin. The pipeline redeployed with 'public' end change this time, and after deployment, the fields (for Years of Operation) shows up.

The strange behaviors of the public frontend described above need some investigation. It feels like the admin connects to the backend that has the database with test data migrated correctly while public connects to the backend that has the database with test data migration incorrectly, but how could that happen?
This probably can be isolated only on 'dev' environment before PR merged into TEST as we were looking into 'test data', if TEST are being tested manually properly by Anne-Marie and Julius.

@ArogeG @basilv
